# Generated by Django 4.2.6 on 2023-10-12 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Kategoriyanyn ady')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriýalar',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Ady')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Goýlan senesi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Täzelenen senesi')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Suraty')),
                ('is_published', models.BooleanField(default=True, verbose_name='Goýlan wagty?')),
                ('slug', models.SlugField(max_length=95, unique=True, verbose_name='url')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Kategoriýa')),
            ],
            options={
                'verbose_name': 'Önüm',
                'verbose_name_plural': 'Önümler',
                'ordering': ['created_at'],
            },
        ),
    ]
