# Generated by Django 4.2.6 on 2023-10-12 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Kategoriýa'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Kategoriýa'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_tk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Kategoriýa'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Ady'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Ady'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tk',
            field=models.CharField(max_length=150, null=True, verbose_name='Ady'),
        ),
    ]
